---
  name: Backport Assistant Runner
  
  on:
    pull_request:
      types:
        - closed
  
  jobs:
    backport:
      if: github.event.pull_request.merged
      runs-on: ubuntu-latest
      container: hashicorpdev/backport-assistant:0.2.0
      steps:
        - name: Run Backport Assistant
          run: |
            backport-assistant backport -automerge
          env:
            BACKPORT_LABEL_REGEXP: "(?P<target>website)/cherrypick"
            BACKPORT_TARGET_TEMPLATE: "stable-{{.target}}"
            GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}